# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_lunch_order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
